import time
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
print("KASCERTOR IS WATCHING YOU!")
time.sleep(5)
